package com.serfagab.app.local

object Contract {

    const val NOMBRE_BASE_DATOS = "serfagab.db"
    const val VERSION_BASE_DATOS = 1

    // TABLA TIPO
    const val TABLA_TIPOU = "tipo"
    const val COLUMNA_TIPOU_ID = "id_tipo"
    const val COLUMNA_TIPOU_DESCRIPCION = "descripcion"

    const val SQL_CREAR_TABLA_TIPOU = """
        CREATE TABLE $TABLA_TIPOU (
        $COLUMNA_TIPOU_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        $COLUMNA_TIPOU_DESCRIPCION TEXT
        )
    """

    // TABLA USUARIO
    const val TABLA_USUARIO = "usuario"
    const val COLUMNA_USUARIO_ID = "id_usuario"
    const val COLUMNA_USUARIO_ID_TIPO = "id_tipo"
    const val COLUMNA_USUARIO_NOMBRES = "nombres"
    const val COLUMNA_USUARIO_APELLIDOS = "apellidos"
    const val COLUMNA_USUARIO_EMAIL = "email"
    const val COLUMNA_USUARIO_LOGIN = "login"
    const val COLUMNA_USUARIO_CLAVE = "clave"
    const val COLUMNA_USUARIO_ACTIVO = "activo"

    const val SQL_CREAR_TABLA_USUARIO = """
        CREATE TABLE $TABLA_USUARIO (
        $COLUMNA_USUARIO_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        $COLUMNA_USUARIO_ID_TIPO INTEGER NOT NULL,
        $COLUMNA_USUARIO_NOMBRES TEXT NOT NULL,
        $COLUMNA_USUARIO_APELLIDOS TEXT NOT NULL,
        $COLUMNA_USUARIO_EMAIL TEXT NOT NULL,
        $COLUMNA_USUARIO_LOGIN TEXT NOT NULL,
        $COLUMNA_USUARIO_CLAVE TEXT NOT NULL,
        $COLUMNA_USUARIO_ACTIVO INTEGER NOT NULL,
        FOREIGN KEY ($COLUMNA_USUARIO_ID_TIPO) REFERENCES $TABLA_TIPOU($COLUMNA_TIPOU_ID)
        )
    """

    // TABLA TIPO MATERIAL
    const val TABLA_TIPO_MATERIAL = "tipo_material"
    const val COLUMNA_TIPO_ID = "id_tipo_material"
    const val COLUMNA_TIPO_NOMBRE = "nombre"
    const val COLUMNA_TIPO_DESCRIPCION = "descripcion"
    const val COLUMNA_TIPO_ACTIVO = "activo"

    const val SQL_CREAR_TABLA_TIPO_MATERIAL = """
        CREATE TABLE $TABLA_TIPO_MATERIAL (
        $COLUMNA_TIPO_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        $COLUMNA_TIPO_NOMBRE TEXT NOT NULL,
        $COLUMNA_TIPO_DESCRIPCION TEXT,
        $COLUMNA_TIPO_ACTIVO INTEGER NOT NULL
        )
    """

    // TABLA PROVEEDOR
    const val TABLA_PROVEEDOR = "proveedor"
    const val COLUMNA_PROVEEDOR_ID = "id_proveedor"
    const val COLUMNA_PROVEEDOR_RAZON_SOCIAL = "razon_social"
    const val COLUMNA_PROVEEDOR_RUC = "ruc"
    const val COLUMNA_PROVEEDOR_CELULAR = "celular"
    const val COLUMNA_PROVEEDOR_EMAIL = "email"
    const val COLUMNA_PROVEEDOR_DESCRIPCION = "descripcion"
    const val COLUMNA_PROVEEDOR_ACTIVO = "activo"

    const val SQL_CREAR_TABLA_PROVEEDOR = """
        CREATE TABLE $TABLA_PROVEEDOR (
        $COLUMNA_PROVEEDOR_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        $COLUMNA_PROVEEDOR_RAZON_SOCIAL TEXT NOT NULL,
        $COLUMNA_PROVEEDOR_RUC TEXT NOT NULL,
        $COLUMNA_PROVEEDOR_CELULAR TEXT NOT NULL,
        $COLUMNA_PROVEEDOR_EMAIL TEXT NOT NULL,
        $COLUMNA_PROVEEDOR_DESCRIPCION TEXT,
        $COLUMNA_PROVEEDOR_ACTIVO INTEGER NOT NULL
        )
    """

    // TABLA MATERIAL
    const val TABLA_MATERIAL = "material"
    const val COLUMNA_MATERIAL_ID = "id_material"
    const val COLUMNA_MATERIAL_ID_TIPO = "id_tipo_material"
    const val COLUMNA_MATERIAL_NOMBRE = "nombre"
    const val COLUMNA_MATERIAL_UNIDAD = "unidad_medida"
    const val COLUMNA_MATERIAL_STOCK = "stock_actual"
    const val COLUMNA_MATERIAL_PRECIO = "precio_referencial"
    const val COLUMNA_MATERIAL_DESCRIPCION = "descripcion"
    const val COLUMNA_MATERIAL_VERSION = "version"
    const val COLUMNA_MATERIAL_ACTIVO = "activo"

    const val SQL_CREAR_TABLA_MATERIAL = """
        CREATE TABLE $TABLA_MATERIAL (
        $COLUMNA_MATERIAL_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        $COLUMNA_MATERIAL_ID_TIPO INTEGER NOT NULL,
        $COLUMNA_MATERIAL_NOMBRE TEXT NOT NULL,
        $COLUMNA_MATERIAL_UNIDAD TEXT NOT NULL,
        $COLUMNA_MATERIAL_STOCK REAL NOT NULL,
        $COLUMNA_MATERIAL_PRECIO REAL NOT NULL,
        $COLUMNA_MATERIAL_DESCRIPCION TEXT,
        $COLUMNA_MATERIAL_VERSION INTEGER NOT NULL DEFAULT 0,
        $COLUMNA_MATERIAL_ACTIVO INTEGER NOT NULL,
        FOREIGN KEY ($COLUMNA_MATERIAL_ID_TIPO) REFERENCES $TABLA_TIPO_MATERIAL($COLUMNA_TIPO_ID)
        )
    """

    // TABLA ORDEN COMPRA
    const val TABLA_ORDEN_COMPRA = "orden_compra"
    const val COLUMNA_ORDEN_COMPRA_ID = "id_orden_compra"
    const val COLUMNA_ORDEN_COMPRA_ID_PROVEEDOR = "id_proveedor"
    const val COLUMNA_ORDEN_COMPRA_ID_USUARIO = "id_usuario"
    const val COLUMNA_ORDEN_COMPRA_OBSERVACIONES = "observaciones"
    const val COLUMNA_ORDEN_COMPRA_FECHA = "fecha"
    const val COLUMNA_ORDEN_COMPRA_TOTAL = "total"
    const val COLUMNA_ORDEN_COMPRA_ESTADO = "estado"
    const val COLUMNA_ORDEN_COMPRA_PENDIENTE_SYNC = "pendiente_sync"

    const val SQL_CREAR_TABLA_ORDEN_COMPRA = """
        CREATE TABLE $TABLA_ORDEN_COMPRA (
        $COLUMNA_ORDEN_COMPRA_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        $COLUMNA_ORDEN_COMPRA_ID_PROVEEDOR INTEGER NOT NULL,
        $COLUMNA_ORDEN_COMPRA_ID_USUARIO INTEGER NOT NULL,
        $COLUMNA_ORDEN_COMPRA_OBSERVACIONES TEXT,
        $COLUMNA_ORDEN_COMPRA_FECHA TEXT NOT NULL,
        $COLUMNA_ORDEN_COMPRA_TOTAL REAL NOT NULL,
        $COLUMNA_ORDEN_COMPRA_ESTADO TEXT NOT NULL,
        $COLUMNA_ORDEN_COMPRA_PENDIENTE_SYNC INTEGER NOT NULL DEFAULT 1,
        FOREIGN KEY ($COLUMNA_ORDEN_COMPRA_ID_PROVEEDOR) REFERENCES $TABLA_PROVEEDOR($COLUMNA_PROVEEDOR_ID),
        FOREIGN KEY ($COLUMNA_ORDEN_COMPRA_ID_USUARIO) REFERENCES $TABLA_USUARIO($COLUMNA_USUARIO_ID)
        )
    """

    // TABLA DETALLE ORDEN COMPRA
    const val TABLA_DETALLE_ORDEN = "detalle_orden"
    const val COLUMNA_DETALLE_ORDEN_ID = "id_detalle_orden"
    const val COLUMNA_DETALLE_ORDEN_ID_MATERIAL = "id_material"
    const val COLUMNA_DETALLE_ORDEN_ID_ORDEN = "id_orden_compra"
    const val COLUMNA_DETALLE_ORDEN_CANTIDAD = "cantidad"
    const val COLUMNA_DETALLE_ORDEN_PRECIO = "precio"
    const val COLUMNA_DETALLE_ORDEN_SUBTOTAL = "subtotal"

    const val SQL_CREAR_TABLA_DETALLE_ORDEN = """
        CREATE TABLE $TABLA_DETALLE_ORDEN (
        $COLUMNA_DETALLE_ORDEN_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        $COLUMNA_DETALLE_ORDEN_ID_MATERIAL INTEGER NOT NULL,
        $COLUMNA_DETALLE_ORDEN_ID_ORDEN INTEGER NOT NULL,
        $COLUMNA_DETALLE_ORDEN_CANTIDAD REAL NOT NULL,
        $COLUMNA_DETALLE_ORDEN_PRECIO REAL NOT NULL,
        $COLUMNA_DETALLE_ORDEN_SUBTOTAL REAL NOT NULL,
        FOREIGN KEY ($COLUMNA_DETALLE_ORDEN_ID_MATERIAL) REFERENCES $TABLA_MATERIAL($COLUMNA_MATERIAL_ID),
        FOREIGN KEY ($COLUMNA_DETALLE_ORDEN_ID_ORDEN) REFERENCES $TABLA_ORDEN_COMPRA($COLUMNA_ORDEN_COMPRA_ID)
        )
    """
}